name: Local Testing

on:  # yamllint disable-line rule:truthy
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 4 1 * *"
  push:
    tags:
      - "*"
    branches:
      - main

permissions: {}

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, macos-14, macos-15-intel, ubuntu-24.04, ubuntu-22.04, ubuntu-24.04-arm, windows-2025, windows-2022]
        qt: [""]
        mesa: [""]
        include:
          - os: ubuntu-22.04
            qt: "pyqt5"
          - os: ubuntu-24.04
            qt: "pyqt6"
          - os: windows-latest
            qt: "pyqt6"
            mesa: "latest"
          - os: ubuntu-latest
            qt: "pyside6"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Test Action
        uses: ./
        with:
          qt: ${{ matrix.qt != '' }}
          mesa3d-release: ${{ matrix.mesa || '24.3.0' }}
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
        with:
          python-version: "3.12"
      - run: pip install pyvista
      - run: python tests/test_pyvista.py
      - run: python -c "import pyvista;print(pyvista.Report())"
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: ${{ matrix.os }}-${{ matrix.qt }}-sphere
          path: sphere.png
          if-no-files-found: error
      - name: Second test of PyVista
        env:
          MATRIX_OS: ${{ matrix.os }}
          MATRIX_QT: ${{ matrix.qt }}
        run: python -c "import os,pyvista;pyvista.Cube().plot(screenshot=os.environ['MATRIX_OS']+'-'+os.environ['MATRIX_QT']+'-cube.png')"
      - name: Test Qt
        if: matrix.qt != ''
        env:
          MATRIX_QT: ${{ matrix.qt }}
        run: |
          set -eo pipefail
          pip install "$MATRIX_QT" matplotlib qtpy
          QT_DEBUG_PLUGINS=1 LIBGL_DEBUG=verbose python tests/test_qt.py
        shell: bash
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: ${{ matrix.os }}-${{ matrix.qt }}-cube
          path: ${{ matrix.os }}-${{ matrix.qt }}-cube.png
          if-no-files-found: error
      - name: Test Vispy Qt
        if: matrix.qt != ''
        run: |
          pip install vispy pillow pyopengl
          python tests/test_vispy_qt.py
        env:
          MATRIX_OS: ${{ matrix.os }}
          MATRIX_QT: ${{ matrix.qt }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        if: matrix.qt != ''
        with:
          name: ${{ matrix.os }}-${{ matrix.qt }}-vispy-volume
          path: ${{ matrix.os }}-${{ matrix.qt }}-vispy-volume.png
