name: Test latest release

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 4 1 * *"

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [macos-14, macos-13, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: pyvista/setup-headless-display-action@5bc8de3bc71fcda7a96439571287a554901541a0 # v4
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: 3.12
      - run: pip install pyvista
      - name: Use PyVista
        env:
          MATRIX_OS: ${{ matrix.os }}
        run: python -c "import pyvista;pyvista.Sphere().plot(screenshot='${MATRIX_OS}-sphere.png')"
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ matrix.os }}-sphere
          path: ${{ matrix.os }}-sphere.png
          if-no-files-found: error
